### ISSUE TITLE
RFC: Powertools libraries naming convention

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda#80]
## Key information

* RFC PR: (leave this empty)
* Related issue(s), if known: n/a
* Area: all
* Meet [tenets](https://github.com/awslabs/aws-lambda-powertools-roadmap#tenets): Yes
* Approved by: 
* Reviewed by: 

## Summary
[summary]: #summary

The goal of this RFC is to have a unique, standardised and easy to understand naming convention for each Powertools library in all places, including across different languages.

## Motivation
[motivation]: #motivation
Currently, in our documentation the library is referred in different ways:
- AWS Lambda Powertools (TypeScript)
- Lambda Powertools TypeScript
- AWS Lambda Powertools TypeScript
- AWS Lambda Powertools for TypeScript

![Screenshot 2022-02-14 at 12 16 03](https://user-images.githubusercontent.com/47529391/153854921-28d9c4ac-bef6-4ed8-b326-1dfeac884233.png)   

![Screenshot 2022-02-14 at 12 16 15](https://user-images.githubusercontent.com/47529391/153854924-5438928c-90dd-496f-b30d-ce01427bb540.png)  

![Screenshot 2022-02-14 at 12 17 08](https://user-images.githubusercontent.com/47529391/153854926-5aa5cbf2-dbbb-4128-9754-2b9bac84b0de.png)  

![Screenshot 2022-02-14 at 12 20 37](https://user-images.githubusercontent.com/47529391/153854927-cf3f6501-6ad4-4bb3-a419-d4e970d738e0.png). 

TypeScript is used here as example, but the same applies to Python, Java, and other upcoming languages.

As the number of languages supported by the AWS Lambda Powertools grows, there is an opportunity to make the name of the project clearer and consistent among different languages/runtime. 
The conversation among maintainers about the library's naming convention was generated by [this comment](https://news.ycombinator.com/item?id=30040757) in this HN thread.

## Proposal
[proposal]: #proposal

The library name of a specific language is "AWS Lambda Powertools for [Language]":
- AWS Lambda Powertools for Python
- AWS Lambda Powertools for Java
- AWS Lambda Powertools for TypeScript

As consequence, all the versions below should be changed accordingly to the new one:
- AWS Lambda Powertools (TypeScript)
- Lambda Powertools TypeScript
- AWS Lambda Powertools TypeScript

**If this feature should be available in other runtimes (e.g. Java), how would this look like to ensure consistency?**

## User Experience

Customers should not be impacted as this does only affect the documentation.

## Drawbacks
[drawbacks]: #drawbacks

N/A

## Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

The maintainers have considered also these versions (TypeScript as example):
- AWS Lambda Powertools TypeScript
- AWS Lambda Powertools (TypeScript)
But AWS Lambda Powertools for TypeScript was the winner.

* **What other designs have been considered? Why not them?**
* **What is the impact of not doing this?**

## Unresolved questions
[unresolved-questions]: #unresolved-questions

## Impacted repositories

https://github.com/awslabs/aws-lambda-powertools-python
https://github.com/awslabs/aws-lambda-powertools-java
https://github.com/awslabs/aws-lambda-powertools-typescript
https://github.com/aws-samples/aws-lambda-powertools-examples

**Comment by dreamorosi** [comment]
Would this change affect also the name of the actual repos on GitHub? I.e. `https://github.com/awslabs/aws-lambda-powertools-typescript` would become `https://github.com/awslabs/aws-lambda-powertools-for-typescript`? 

Other than that 100% in favor with standardising the names using your proposal.

**Comment by sliedig** [comment]
@dreamorosi No, the repo names stay the same

**Comment by heitorlessa** [comment]
@saragerion thank you for kicking this off! We've got all leads vote so we can go ahead and implement the new convention - AWS Lambda Powertools for **<Runtime>**.

**Comment by michaelbrewer** [comment]
I worked on a PR to try this before to be `AWS Lambda Powertools (<Language>)` for all versions, but this seems to be another version of that.

**Comment by heitorlessa** [comment]
Yes @michaelbrewer, this is what all maintainers across all languages have agreed.

---

@saragerion @sliedig @dreamorosi @pankajagrawal16 @am29d @mploski @flochaz as I make several changes in the Python docs, package metadata, etc., I noticed we should have an exception: a shorter name after the long name has been used, just like we have in some AWS Services official branding. 

I'd suggest subsequent references can optionally use `AWS Lambda Powertools`.

A few examples where we already used `AWS Lambda Powertools for Python` multiple times in the same doc, but use the shorter version to remain on brand and not further prolong longer sentences, code snippets titles, banners with limited space:

> Refactoring with AWS Lambda Powertools Logger (code snippet)

> Let's include AWS Lambda Powertools as a dependency in `requirement.txt`

> As we already have AWS Lambda Powertools as a dependency, we can simply import [Logger](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/)

> Let's explore how we can instrument our code with [AWS X-Ray SDK](https://docs.aws.amazon.com/xray-sdk-for-python/latest/reference/index.html){target="_blank"}, and then simplify it with [AWS Lambda Powertools Tracer](../core/tracer.md){target="_blank"} feature.

**Comment by michaelbrewer** [comment]
Cool. Just wondering, as I made PRs earlier to correct this. Good that you have internally agreed on new names.

**Comment by saragerion** [comment]
Note, after further internal discussion among maintainers, we have agreed that the "short" version of the library can be just "Powertools". 
We will make decision explicit in the homepage of the documentation, the second time that the name it's referenced. 
Example for Typescript:

> The AWS Lambda Powertools for TypeScript utilities (which from here will be referred as Powertools) ...

**Comment by michaelbrewer** [comment]
My recommendation is limit the use of "AWS Lambda Powertools For XXXX" to the main titles only and use the short name "AWS Lambda Powertools" for the rest of the docs or when referencing the collective. 

Once within the main docs, I don't see the need to use the fully qualified name, and just use "AWS Lambda Powertools", at this point you know you are within the scope of that language. 

The main package name does not need to change as it is implicit (pip (python) version is for python). 

The repo name is already explicit ie: "aws-lambda-powertools-xxxx", and renaming would break any existing clones of the repo.

**Comment by michaelbrewer** [comment]
Nice. Love it. Easier to share and talk about once the context was set. Potentially allowing for shorter package names and variable names if there are v2 versions.

**Comment by leandrodamascena** [comment]
Closing this issue as we have the naming convention in place - Powertools for AWS Lambda (Language)
